### ISSUE TITLE
Possible recent regression?

### ISSUE THREAD

**Issue by purpleidea** [libvirt/libvirt-go#10]
Are these build errors due to something that regressed recently in git master here, or something elsewhere? We build at least daily and an mgmt user/hacker saw them in the build logs:

```
could not determine kind of name for C.VIR_PERF_PARAM_ALIGNMENT_FAULTS
could not determine kind of name for C.VIR_PERF_PARAM_REF_EMULATION_FAULTS
```
https://travis-ci.org/taksuyu/mgmt/jobs/208767587

Thanks,
James

**Comment by berrange** [comment]
Yes the recent perf commit broke the build. Fix in

commit c9d3e198a9d1940b74de32426f03d249125cc9d5
Author: Daniel P. Berrange <berrange@redhat.com>
Date:   Tue Mar 7 23:08:16 2017 +0000

    Fix typos in VIR_PERF constants from previous commit
    
    Signed-off-by: Daniel P. Berrange <berrange@redhat.com>
