### ISSUE TITLE
Development status of repository

### ISSUE THREAD

**Issue by rushiagr** [libvirt/libvirt-go#14]
It would help people evaluate the repository if the development status of code base is mentioned in the readme (alpha, beta, production-stable, etc). Thanks.

**Comment by berrange** [comment]
Fixed in

commit d820b7c5d10ec4dd689ea81bebc567413a42c8a4
Author: Daniel P. Berrange <berrange@redhat.com>
Date:   Tue Apr 25 15:48:29 2017 +0100

    Add note about development status
    
    Signed-off-by: Daniel P. Berrange <berrange@redhat.com>
