### ISSUE TITLE
JSON marshal on DomainEventLifecycle

### ISSUE THREAD

**Issue by danielkucera** [libvirt/libvirt-go#19]
I'm always getting Detail: 0 when I try to marshal DomainEventLifecycle into JSON. When I Printf the variable, detail is displayed ok:

```
Domain event="shutdown" detail="finished"
{"Event":6,"Detail":0}
Domain event="stopped" detail="shutdown"
{"Event":5,"Detail":0}
```

**Comment by purpleidea** [comment]
It looks like it has a String method which is what you see when you print:

```
func (e DomainEventLifecycle) String() string {
```

And inside it:

361:	DOMAIN_EVENT_SHUTDOWN_FINISHED = DomainEventShutdownDetailType(C.VIR_DOMAIN_EVENT_SHUTDOWN_FINISHED)

So maybe that value is actually zero??

**Comment by berrange** [comment]
detail=="finished" is string repr of  libvirt.DOMAIN_EVENT_SHUTDOWN_FINISHED which has value 0.

detail=="shutdown" is string repr of libvirt.DOMAIN_EVENT_STOPPED_SHUTDOWN which again has value 0. 

So everything's working as intended.

**Comment by purpleidea** [comment]
tfw when "machine" Daniel Berrange beats you to the answer by 10 seconds :P

**Comment by danielkucera** [comment]
OK guys, sorry for that, my bad.
