### ISSUE TITLE
Domain block copy function doesn't work

### ISSUE THREAD

**Issue by gofort** [libvirt/libvirt-go#2]
Domain block copy function doesn't work. Behaviour of this function doesn't change even if I change params. 

`
	from := fmt.Sprintf("%s/disks/%s.img", ct.StoragePath, domainuuid)
	to := fmt.Sprintf("%s/backups/%s_%d.img", ct.StoragePath, domainuuid, time.Now().Unix())

	params := libvirt.DomainBlockCopyParameters{
		BandwidthSet:   true,
		Bandwidth:      2147483648,
		GranularitySet: true,
		Granularity:    512,
	}

	xmlTmpl := fmt.Sprintf("<disk type='file'>
	<driver type='qcow2'/>
	<source file='%s'/>
	</disk>", to)

	// Undefine if domain is not transient
	//err = domain.Undefine()
	//if err != nil {
	//	ct.Log.Error(err)
	//	return false, err
	//}

	err = domain.BlockCopy(from, xmlTmpl, &params, libvirt.DOMAIN_BLOCK_COPY_SHALLOW)
	if err != nil {
		ct.Log.Error(err)
		return false, err
	}
`

`SIGABRT: abort
PC=0x7f8c805a5428 m=10
signal arrived during cgo execution

goroutine 24 [syscall, locked to thread]:
runtime.cgocall(0x8ceb50, 0xc820045318, 0xc800000000)
	/usr/lib/go-1.6/src/runtime/cgocall.go:123 +0x11b fp=0xc8200452e0 sp=0xc8200452b0
github.com/libvirt/libvirt-go._Cfunc_free(0x7f8c5c000b50)
	??:0 +0x36 fp=0xc820045318 sp=0xc8200452e0
github.com/libvirt/libvirt-go.(*Domain).BlockCopy(0xc820154070, 0xc82012a5c0, 0x39, 0xc82014c240, 0x8c, 0xc820128870, 0x1, 0x7f8c6ee634f0, 0xc8201288d0)
	/root/development/projects/vs-agent/vendor/src/github.com/libvirt/libvirt-go/domain.go:1966 +0x55f fp=0xc820045440 sp=0xc820045318
main.DomainBackup(0xc820073ce0, 0x24, 0x0, 0x0, 0x0)
	/root/development/projects/vs-agent/src/vs-agent/domain.go:303 +0xa3f fp=0xc820045620 sp=0xc820045440
runtime.call64(0xc82012a580, 0xbfb730, 0xc820128840, 0x1000000028)
	/usr/lib/go-1.6/src/runtime/asm_amd64.s:473 +0x3e fp=0xc820045668 sp=0xc820045620
reflect.Value.call(0x9b8400, 0xbfb730, 0x13, 0xad92b8, 0x4, 0xc82012e8a0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/go-1.6/src/reflect/value.go:435 +0x120d fp=0xc8200459b8 sp=0xc820045668
reflect.Value.Call(0x9b8400, 0xbfb730, 0x13, 0xc82012e8a0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/reflect/value.go:303 +0xb1 fp=0xc820045a18 sp=0xc8200459b8
github.com/RichardKnop/machinery/v1.TryCall(0x9b8400, 0xbfb730, 0x13, 0xc82012e8a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:249 +0xef fp=0xc820045a98 sp=0xc820045a18
github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc820100200, 0xc8200e42c0, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:91 +0x64a fp=0xc820045bd8 sp=0xc820045a98
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consumeOne(0xc8201040c0, 0x7f8c8136cb38, 0xc820184100, 0x0, 0xc82019a020, 0x10, 0x0, 0x0, 0x2, 0x0, ...)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:175 +0x5ba fp=0xc820045e18 sp=0xc820045bd8
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume.func2(0xc8201040c0, 0xc820096640, 0x7f8c6ee5e000, 0xc820100200, 0xc82006d140, 0x5, 0xc82006d0e0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:207 +0x77 fp=0xc820045f68 sp=0xc820045e18
runtime.goexit()
	/usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820045f70 sp=0xc820045f68
created by github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:212 +0x277

goroutine 1 [chan receive]:
main.main()
	/root/development/projects/vs-agent/src/vs-agent/main.go:60 +0x5bf

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.6/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/lib/go-1.6/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go-1.6/src/os/signal/signal_unix.go:28 +0x37

goroutine 21 [chan receive]:
vs-agent/context.virtConnect(0xc82006cf00)
	/root/development/projects/vs-agent/src/vs-agent/context/context.go:103 +0x5c
created by vs-agent/context.NewContext.func1
	/root/development/projects/vs-agent/src/vs-agent/context/context.go:78 +0x4e4

goroutine 34 [syscall, locked to thread]:
github.com/libvirt/libvirt-go._Cfunc_virEventRunDefaultImpl(0x7f8c00000000)
	??:0 +0x45
github.com/libvirt/libvirt-go.EventRunDefaultImpl(0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/libvirt/libvirt-go/events.go:53 +0x28
vs-agent/context.libvirtEvents(0xc82006cf00)
	/root/development/projects/vs-agent/src/vs-agent/context/context.go:148 +0x178
created by vs-agent/context.NewContext.func1
	/root/development/projects/vs-agent/src/vs-agent/context/context.go:88 +0x549

goroutine 35 [chan receive]:
github.com/RichardKnop/machinery/v1.(*Worker).Launch(0xc820100160, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:50 +0x11a6
created by main.main
	/root/development/projects/vs-agent/src/vs-agent/main.go:52 +0x35b

goroutine 36 [chan receive]:
github.com/RichardKnop/machinery/v1.(*Worker).Launch(0xc820100200, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:50 +0x11a6
created by main.main
	/root/development/projects/vs-agent/src/vs-agent/main.go:53 +0x384

goroutine 37 [chan receive]:
github.com/RichardKnop/machinery/v1.(*Worker).Launch(0xc8201000c0, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:50 +0x11a6
created by main.main
	/root/development/projects/vs-agent/src/vs-agent/main.go:54 +0x3ad

goroutine 38 [select, locked to thread]:
runtime.gopark(0xbfbf18, 0xc8200fa728, 0xade0b8, 0x6, 0x18, 0x2)
	/usr/lib/go-1.6/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc8200fa728, 0x0, 0x18)
	/usr/lib/go-1.6/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc8200fa728)
	/usr/lib/go-1.6/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/lib/go-1.6/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1

goroutine 50 [select]:
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume(0xc8201040c0, 0xc82006d020, 0x7f8c6ee5e000, 0xc820100200, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:196 +0x2d5
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).StartConsuming(0xc8201040c0, 0xb6c1c0, 0x18, 0x7f8c6ee5e000, 0xc820100200, 0x0, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:88 +0x7bd
github.com/RichardKnop/machinery/v1.(*Worker).Launch.func1(0x7f8c81324000, 0xc8201040c0, 0xc820100200, 0xc820132060)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:39 +0xa0
created by github.com/RichardKnop/machinery/v1.(*Worker).Launch
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:48 +0x116d

goroutine 3 [select]:
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume(0xc820104080, 0xc820132660, 0x7f8c6ee5e000, 0xc820100160, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:196 +0x2d5
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).StartConsuming(0xc820104080, 0xb6c1e0, 0x18, 0x7f8c6ee5e000, 0xc820100160, 0x0, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:88 +0x7bd
github.com/RichardKnop/machinery/v1.(*Worker).Launch.func1(0x7f8c81324000, 0xc820104080, 0xc820100160, 0xc820130060)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:39 +0xa0
created by github.com/RichardKnop/machinery/v1.(*Worker).Launch
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:48 +0x116d

goroutine 39 [select]:
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume(0xc820104000, 0xc820130480, 0x7f8c6ee5e000, 0xc8201000c0, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:196 +0x2d5
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).StartConsuming(0xc820104000, 0xb6c200, 0x1c, 0x7f8c6ee5e000, 0xc8201000c0, 0x0, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:88 +0x7bd
github.com/RichardKnop/machinery/v1.(*Worker).Launch.func1(0x7f8c81324000, 0xc820104000, 0xc8201000c0, 0xc82010c180)
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:39 +0xa0
created by github.com/RichardKnop/machinery/v1.(*Worker).Launch
	/root/development/projects/vs-agent/vendor/src/github.com/RichardKnop/machinery/v1/worker.go:48 +0x116d

goroutine 40 [IO wait]:
net.runtime_pollWait(0x7f8c6ee5ef20, 0x72, 0xc820163000)
	/usr/lib/go-1.6/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820152060, 0x72, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820152060, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820152000, 0xc820163000, 0x1000, 0x1000, 0x0, 0x7f8c81364028, 0xc82006e0a0)
	/usr/lib/go-1.6/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820160000, 0xc820163000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc82010c3c0)
	/usr/lib/go-1.6/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc82010c3c0, 0xc82012cc68, 0x7, 0x7, 0x1, 0x0, 0x0)
	/usr/lib/go-1.6/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f8c81324210, 0xc82010c3c0, 0xc82012cc68, 0x7, 0x7, 0x7, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/io/io.go:297 +0xe6
io.ReadFull(0x7f8c81324210, 0xc82010c3c0, 0xc82012cc68, 0x7, 0x7, 0xc82010c360, 0x0, 0x0)
	/usr/lib/go-1.6/src/io/io.go:315 +0x62
github.com/streadway/amqp.(*reader).ReadFrame(0xc820149ee0, 0x0, 0x0, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/read.go:49 +0xbd
github.com/streadway/amqp.(*Connection).reader(0xc82010a360, 0x7f8c81324178, 0xc820160000)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:503 +0x172
created by github.com/streadway/amqp.Open
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:221 +0x3e8

goroutine 52 [IO wait]:
net.runtime_pollWait(0x7f8c6ee5efe0, 0x72, 0xc82016a000)
	/usr/lib/go-1.6/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82014e060, 0x72, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82014e060, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82014e000, 0xc82016a000, 0x1000, 0x1000, 0x0, 0x7f8c81364028, 0xc82006e0a0)
	/usr/lib/go-1.6/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820154008, 0xc82016a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc82010c420)
	/usr/lib/go-1.6/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc82010c420, 0xc82019a037, 0x7, 0x7, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f8c81324210, 0xc82010c420, 0xc82019a037, 0x7, 0x7, 0x7, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/io/io.go:297 +0xe6
io.ReadFull(0x7f8c81324210, 0xc82010c420, 0xc82019a037, 0x7, 0x7, 0xc820132240, 0x0, 0x0)
	/usr/lib/go-1.6/src/io/io.go:315 +0x62
github.com/streadway/amqp.(*reader).ReadFrame(0xc820173ee0, 0x0, 0x0, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/read.go:49 +0xbd
github.com/streadway/amqp.(*Connection).reader(0xc820168000, 0x7f8c81324178, 0xc820154008)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:503 +0x172
created by github.com/streadway/amqp.Open
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:221 +0x3e8

goroutine 53 [IO wait]:
net.runtime_pollWait(0x7f8c6ee5ee60, 0x72, 0xc82016c000)
	/usr/lib/go-1.6/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820150060, 0x72, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820150060, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820150000, 0xc82016c000, 0x1000, 0x1000, 0x0, 0x7f8c81364028, 0xc82006e0a0)
	/usr/lib/go-1.6/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820154018, 0xc82016c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820132420)
	/usr/lib/go-1.6/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820132420, 0xc82000ef38, 0x7, 0x7, 0x6, 0x0, 0x0)
	/usr/lib/go-1.6/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f8c81324210, 0xc820132420, 0xc82000ef38, 0x7, 0x7, 0x7, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/io/io.go:297 +0xe6
io.ReadFull(0x7f8c81324210, 0xc820132420, 0xc82000ef38, 0x7, 0x7, 0xc8201323c0, 0x0, 0x0)
	/usr/lib/go-1.6/src/io/io.go:315 +0x62
github.com/streadway/amqp.(*reader).ReadFrame(0xc820145ee0, 0x0, 0x0, 0x0, 0x0)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/read.go:49 +0xbd
github.com/streadway/amqp.(*Connection).reader(0xc820168120, 0x7f8c81324178, 0xc820154018)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:503 +0x172
created by github.com/streadway/amqp.Open
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:221 +0x3e8

goroutine 41 [select]:
github.com/streadway/amqp.(*Connection).heartbeater(0xc82010a360, 0x2540be400, 0xc82010c480)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:533 +0x506
created by github.com/streadway/amqp.(*Connection).openTune
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:754 +0x805

goroutine 4 [select]:
github.com/streadway/amqp.(*Connection).heartbeater(0xc820168000, 0x2540be400, 0xc820130120)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:533 +0x506
created by github.com/streadway/amqp.(*Connection).openTune
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:754 +0x805

goroutine 54 [select]:
github.com/streadway/amqp.(*Connection).heartbeater(0xc820168120, 0x2540be400, 0xc820132480)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:533 +0x506
created by github.com/streadway/amqp.(*Connection).openTune
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/connection.go:754 +0x805

goroutine 55 [chan receive]:
github.com/streadway/amqp.bufferDeliveries(0xc8201326c0, 0xc820132660)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/consumers.go:38 +0x7b
created by github.com/streadway/amqp.(*consumers).add
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/consumers.go:74 +0x10b

goroutine 6 [chan receive]:
github.com/streadway/amqp.bufferDeliveries(0xc8201304e0, 0xc820130480)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/consumers.go:38 +0x7b
created by github.com/streadway/amqp.(*consumers).add
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/consumers.go:74 +0x10b

goroutine 22 [chan receive]:
github.com/streadway/amqp.bufferDeliveries(0xc82006d080, 0xc82006d020)
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/consumers.go:38 +0x7b
created by github.com/streadway/amqp.(*consumers).add
	/root/development/projects/vs-agent/vendor/src/github.com/streadway/amqp/consumers.go:74 +0x10b

rax    0x0
rbx    0x55
rcx    0x7f8c805a5428
rdx    0x6
rdi    0x7c5a
rsi    0x7c62
rbp    0x7f8c6de5ab10
rsp    0x7f8c6de5a778
r8     0x10
r9     0x400
r10    0x8
r11    0x206
r12    0x55
r13    0x7f8c6de5a928
r14    0x7f8c6de5a928
r15    0x2
rip    0x7f8c805a5428
rflags 0x206
cs     0x33
fs     0x0
gs     0x0`

**Comment by berrange** [comment]
Thanks for the report, I'll write a integration test to cover this scenario and figure out a fix

**Comment by berrange** [comment]
Fun, this is non-deterministic - works locally for me but fails under travis some of the time

**Comment by berrange** [comment]
Turns out to be memory corruption from failing to setup typed parameters correctly, but only impacts certain libvirt versions. It is fixed in

commit 1dfd5832a97b19c1ac136973a495c085f66ca21f
Author: Daniel P. Berrange <berrange@redhat.com>
Date:   Tue Dec 20 14:33:28 2016 +0000

    Ensure we set parameter type correctly
    
    When allocating a new virTypedParameter array we were forgetting
    to initialize the parameter type, causing non-deterministic
    failures
    
    Signed-off-by: Daniel P. Berrange <berrange@redhat.com>
