### ISSUE TITLE
Did git master just break?

### ISSUE THREAD

**Issue by purpleidea** [libvirt/libvirt-go#20]
```
# github.com/libvirt/libvirt-go

/tmp/go-build756541303/github.com/libvirt/libvirt-go/_obj/stream_cfuncs.cgo2.o: In function `virStreamSparseSendAll_cgo':

../../libvirt/libvirt-go/stream_cfuncs.go:95: undefined reference to `assert'

/tmp/go-build756541303/github.com/libvirt/libvirt-go/_obj/stream_cfuncs.cgo2.o: In function `virStreamSparseRecvAll_cgo':

../../libvirt/libvirt-go/stream_cfuncs.go:112: undefined reference to `assert'

collect2: error: ld returned 1 exit status
```

Or is it my fault somehow? Thanks

**Comment by purpleidea** [comment]
(For reference: our git master cron builds started failing... Full logs...)

https://travis-ci.org/purpleidea/mgmt/jobs/236899475#L715

This looks like the issue: https://github.com/libvirt/libvirt-go/commit/41d08218de5e4c4b3aff4220e18ae5212a7c360f

Which seems to be present in your CI too ! :)

https://travis-ci.org/libvirt/libvirt-go/jobs/236443990#L2988

I guess this is a +1 vote for not pushing to your master if the builds are broken.

Thanks

**Comment by berrange** [comment]
Of course I test before pushing to master, but I can't manually test every combination - that's what the CI is there to detect

**Comment by purpleidea** [comment]
I meant something along the lines of this might help:

https://ttboj.wordpress.com/2016/02/16/introducing-git-tpush/

Thanks!
