### ISSUE TITLE
gotype errors in git tip

### ISSUE THREAD

**Issue by purpleidea** [libvirt/libvirt-go#22]
I haven't looked into these errors yet, but I recently noticed that my automated tests on git tip recently started failing due to `gotype` errors:

See: https://travis-ci.org/purpleidea/mgmt/jobs/266164065#L949

Heads up in case the solution/fix is obvious to anyone who wants to look into this. It might just be something that upstream golang broke.

HTH, feel free to close if you think it's unnecessary noise, I won't be offended.

Thanks,
James

```
resources/virt.go:162:31:error: cannot use libvirt.DOMAIN_VCPU_MAXIMUM (constant unknown with invalid type) as github.com/libvirt/libvirt-go.DomainVcpuFlags value in argument to dom.GetVcpusFlags (gotype)

resources/virt.go:235:5:error: cannot use libvirt.CRED_AUTHNAME (constant unknown with invalid type) as github.com/libvirt/libvirt-go.ConnectCredentialType value in array or slice literal (gotype)

resources/virt.go:235:28:error: cannot use libvirt.CRED_PASSPHRASE (constant unknown with invalid type) as github.com/libvirt/libvirt-go.ConnectCredentialType value in array or slice literal (gotype)

resources/virt.go:471:33:error: cannot use libvirt.DOMAIN_START_PAUSED (constant unknown with invalid type) as github.com/libvirt/libvirt-go.DomainCreateFlags value in argument to dom.CreateWithFlags (gotype)

resources/virt.go:536:33:error: cannot use libvirt.DOMAIN_START_PAUSED (constant unknown with invalid type) as github.com/libvirt/libvirt-go.DomainCreateFlags value in argument to dom.CreateWithFlags (gotype)

resources/virt.go:649:31:error: cannot use libvirt.DOMAIN_VCPU_GUEST (constant unknown with invalid type) as github.com/libvirt/libvirt-go.DomainVcpuFlags value in argument to dom.GetVcpusFlags (gotype)

resources/virt.go:658:42:error: cannot use libvirt.DOMAIN_VCPU_GUEST (constant unknown with invalid type) as github.com/libvirt/libvirt-go.DomainVcpuFlags value in argument to dom.SetVcpusFlags (gotype)

resources/virt.go:793:34:error: cannot use libvirt.DOMAIN_XML_INACTIVE (constant unknown with invalid type) as github.com/libvirt/libvirt-go.DomainXMLFlags value in argument to dom.GetXMLDesc (gotype)
```

**Comment by purpleidea** [comment]
It seems this only happens in golang 1.9+

**Comment by berrange** [comment]
The integration_test.go covers passing libvirt.DOMAIN_START_PAUSED to dom.CreateWithFlags, and that compiles & runs fine with go 1.9:

https://travis-ci.org/libvirt/libvirt-go

So I don't see anything that needs fixing in libvirt here. This is simply a tools bug.

**Comment by jonathangold** [comment]
@purpleidea It appears this issue is caused by gotype's choice to use the source importer for go 1.9. According to https://golang.org/pkg/go/importer/#For  

> if the compiler argument is "source" [...] if the package API depends on cgo-defined entities, the type checker won't have access to those.

This issue affects more than just gometalinter. Any tool that switched to the source importer for go 1.9 breaks compatibility with projects that use cgo imports.

**Comment by purpleidea** [comment]
@jonathangold Thanks for tracking this down! Is there an upstream (in golang) issue we can tag or open?

**Comment by jonathangold** [comment]
@purpleidea Given your familiarity with the go ecosystem, it would be helpful to chat about the appropriate issue(s) to open and/or tag.
