### ISSUE TITLE
Problem with qemu-kvm domain and FSTrim - cannot set nil

### ISSUE THREAD

**Issue by mrqwer88** [libvirt/libvirt-go#23]
Hello!

I have problem with 
```
func (d *Domain) FSTrim(mount string, minimum uint64, flags uint32) error
```
https://github.com/libvirt/libvirt-go/blob/master/domain.go#L3795
It can get and send as mount only string, but I need to send **nil** ( NULL in original -  in virsh it looks like 
```
const char *mountPoint = NULL;
```
as example - https://libvirt.org/git/?p=libvirt.git;a=blob;f=tools/virsh-domain.c;h=40f16738661fd1faedb4f9eb8d45022ea75d7bc5;hb=HEAD#l13319)

Because it not work with any  defined vaules in qemu - 
```
    if (mountPoint) {
        virReportError(VIR_ERR_ARGUMENT_UNSUPPORTED, "%s", 
                       _("Specifying mount point "
                         "is not supported for now"));
        return -1;
    }
```
https://libvirt.org/git/?p=libvirt.git;a=blob;f=src/qemu/qemu_driver.c;h=e9f07c6e763fd4e8886986af4152bcccb48312f7;hb=HEAD#l18516

Now with libvirt-go I have only error
```
virError(Code=74, Domain=10, Message='argument unsupported: Specifying mount point is not supported for now')
```
( or `cannot use nil as type string in argument to vm.FSTrim`) 
when I try use FSTrim function.

Do I something wrong or it need hack in FSTrim to send nil as mount point ?

Thanks in advance!

**Comment by berrange** [comment]
Fixed in this

commit 1204f37aee137897a59b3cd7bf1dbb31e11532a9 (HEAD -> master, origin/master, origin/HEAD)
Author: Daniel P. Berrange <berrange@redhat.com>
Date:   Wed Aug 30 16:34:55 2017 +0100

    Allow passing NULL mount for FSTrim
    
    Signed-off-by: Daniel P. Berrange <berrange@redhat.com>



Use "" in go to pass a NULL

**Comment by mrqwer88** [comment]
Thanks a lot!
