### ISSUE TITLE
Add getDomain functions as exportables

### ISSUE THREAD

**Issue by s3rj1k** [libvirt/libvirt-go#24]
Below is list of functions that needs to be exported

```
func getDomainStatsBalloonFieldInfo

func getDomainStatsVcpuFieldInfo

func getDomainStatsNetFieldInfo

func getDomainStatsBlockFieldInfo

func getDomainStatsPerfFieldInfo

func getDomainStatsLengthsFieldInfo

func getMemoryParameterFieldInfo

func getDomainStatsStateFieldInfo

func getDomainStatsCPUFieldInfo

func getDomainStatsLengthsFieldInfo
```

**Comment by berrange** [comment]
Why do you think they need to be exported ? They are internal helper APIs used by other functions that are exported.

**Comment by s3rj1k** [comment]
@berrange to use them for parsing returned data from GetAllDomainStats function

**Comment by s3rj1k** [comment]
Currently this helper functions are exported
```
DomainStatsState
DomainShutoffReason
DomainCrashedReason
DomainShutdownReason
DomainPausedReason
DomainBlockedReason
DomainRunningReason
DomainNostateReason
```
is this intentional or accidental?

**Comment by berrange** [comment]
That doesn't make any sense at all - GetAllDomainStats returns a struct with explicit fields for each item of data. There's no parsing involved.

Those other functions you mention are not functions - they're types for enumerated constants.

**Comment by s3rj1k** [comment]
@berrange Thanks for info, figured it out.

Closing issue.
