### ISSUE TITLE
virDomainGetConnect

### ISSUE THREAD

**Issue by s3rj1k** [libvirt/libvirt-go#25]
Is it possible to add this exported function, `virDomainGetConnect`?

So one could easily get `*libvirt.Connect` to hypervisor from `libvirt.Domain`

**Comment by berrange** [comment]
For some reason I skipped all these, but I don't recall why. It seems reasonable to expose all the virXXXXGetConnect methods

**Comment by s3rj1k** [comment]
https://github.com/libvirt/libvirt-go/pull/27

**Comment by s3rj1k** [comment]
Bumping issue, @berrange cat this be merged to master?
