### ISSUE TITLE
virsh net-dumpxml and func (n *Network) GetXMLDesc inconsistency

### ISSUE THREAD

**Issue by s3rj1k** [libvirt/libvirt-go#30]
When using virsh net-dumpxml on defined network we can see this kind of xml:
```
<network connections='1'>
  <name>pf-enp6s0f0</name>
  <uuid>c8ac98ff-a7d2-4253-9b66-a23a9e468ed2</uuid>
  <forward mode='hostdev' managed='yes'>
    <driver name='vfio'/>
    <address type='pci' domain='0x0000' bus='0x06' slot='0x10' function='0x0'/>
  </forward>
</network>
```

when using GetXMLDesc

```
<network>
  <name>pf-enp6s0f0</name>
  <uuid>c8ac98ff-a7d2-4253-9b66-a23a9e468ed2</uuid>
  <forward mode='hostdev' managed='yes'>
    <driver name='vfio'/>
    <address type='pci' domain='0x0000' bus='0x06' slot='0x10' function='0x0'/>
  </forward>
</network>
```

difference in presence of optional parameter connections - " if present, specifies the number of guest interfaces currently connected via this network"

is this issue related to libvirt-go api binding or this is an upstream bug?

**Comment by berrange** [comment]
It sounds like in one case the network was active and in the other case it was inactive. connections=N is only present for active networks.

**Comment by berrange** [comment]
Closing this because the go bindings don't influence what libvirt returns in the XML doc
