### ISSUE TITLE
How to list block devices for domain

### ISSUE THREAD

**Issue by cha87de** [libvirt/libvirt-go#31]
Is there a method I cannot find for listing all block devices of a libvirt domain?

For network interfaces I found `func (d *Domain) ListAllInterfaceAddresses(src DomainInterfaceAddressesSource) ([]DomainInterface, error)` and I'm wondering if there's a similar function for block devices?

Thanks in advance!

**Comment by berrange** [comment]
Generally speaking libvirt does not aim to provide APIs to query different aspects of guest configuration. Apps are expected to query the XML config for the guest to get this info.  The libvirt-go-xml  library makes it much easier to get data by giving you pre-built XML parser -> Go structs.

**Comment by cha87de** [comment]
Thanks for the clarification.
