### ISSUE TITLE
unable to run libvirt-go in docker container

### ISSUE THREAD

**Issue by Sheshagiri-RVBD** [libvirt/libvirt-go#33]
I'm trying to get list of vm's running on my hypervisor using the binary generated from the below snippet
```go
import (
   "log"
    libvirt "github.com/libvirt/libvirt-go"
)
func main(){
	conn, err := libvirt.NewConnect("qemu+unix:///system?socket=/run/libvirt/libvirt-sock")
	if err != nil {
		log.Printf("Error %v",err)
	}
	defer conn.Close()

	doms, err := conn.ListAllDomains(libvirt.CONNECT_LIST_DOMAINS_RUNNING)
	if err != nil {
		log.Printf("Error %v",err)
	}

	log.Printf("%d running domains:\n", len(doms))
	for _, dom := range doms {
		name, err := dom.GetName()
		if err == nil {
			log.Printf("  %s\n", name)
		}
		dom.Free()
	}
}
```
I'm running the container(*ubuntu:16.04*) as
`docker run --privileged -it -v /run/libvirt/libvirt-sock:/run/libvirt/libvirt-sock -v /var/lib/libvirt/:/var/lib/libvirt/ <container-name> /<binary-of-above-code>` and I see the following error
`/<binary-of-above-code>: error while loading shared libraries: libvirt-lxc.so.0: cannot open shared object file: No such file or directory`

any help would be much appreciated, should I install libvirt on the docker container as well ?

**Comment by berrange** [comment]
You need to actually install libvirt in the container so the Go binding can load the libvirt libraries.

**Comment by Sheshagiri-RVBD** [comment]
@berrange thanks for the prompt response.
