### ISSUE TITLE
undefined: Connect,Domain,Interface ..

### ISSUE THREAD

**Issue by hexfusion** [libvirt/libvirt-go#35]
### ENV
* distro: 4.16.2-2-ARCH

* (libvirt) 4.2.0

* go1.10.1 linux/amd64

### Problem

$ go get -u github.com/libvirt/libvirt-go

$ go test -tags api github.com/libvirt/libvirt-go

```
 github.com/libvirt/libvirt-go
./connect_test.go:35:29: undefined: Connect
./domain_test.go:35:26: undefined: Domain
./domain_test.go:35:35: undefined: Connect
./domain_test.go:50:29: undefined: Domain
./domain_test.go:50:38: undefined: Connect
./domain_test.go:66:35: undefined: Domain
./domain_test.go:66:44: undefined: Connect
./interface_test.go:35:39: undefined: Interface
./interface_test.go:35:51: undefined: Connect
./network_test.go:51:41: undefined: Network
./network_test.go:51:41: too many errors
FAIL	github.com/libvirt/libvirt-go [build failed]
```

Trying to shed some light on this, andy help would be great.

ref: https://github.com/dmacvicar/terraform-provider-libvirt/issues/280

**Comment by berrange** [comment]
Those commands complete for me without any error, same go version as you, but on Fedora.

**Comment by hexfusion** [comment]
hi @berrange what version of libvirt are you running?

**Comment by hexfusion** [comment]
Are any automated testing suites run against the libvirt 4 API?

**Comment by berrange** [comment]
It works with any version of libvirt i try, including 4.2.0. Perhaps suspect some rogue Go related environment variable

**Comment by berrange** [comment]
The version of libvirt involved has no bearing on whether the interfaces or methods exist - the code is conditionally built so missing methods will simply generate a runtime error when invoked.

**Comment by hexfusion** [comment]
> It works with any version of libvirt i try, including 4.2.0. Perhaps suspect some rogue Go related environment variable

go env
```
GOARCH="amd64"
GOBIN=""
GOCACHE="off"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/samb/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build595047437=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by berrange** [comment]
This is suspicious:

CGO_ENABLED="0"

The Libvirt bindings use cgo.

**Comment by hexfusion** [comment]
@berrange thanks a lot sir for your help.
