### ISSUE TITLE
Something just broke the builds

### ISSUE THREAD

**Issue by purpleidea** [libvirt/libvirt-go#36]
From: https://travis-ci.org/purpleidea/mgmt/jobs/393804740#L1326

```
../../libvirt/libvirt-go/connect.go:2790:3: could not determine kind of name for C.VIR_NODE_SEV_CBITPOS
../../libvirt/libvirt-go/connect.go:2786:3: could not determine kind of name for C.VIR_NODE_SEV_CERT_CHAIN
../../libvirt/libvirt-go/connect.go:2782:3: could not determine kind of name for C.VIR_NODE_SEV_PDH
../../libvirt/libvirt-go/connect.go:2794:3: could not determine kind of name for C.VIR_NODE_SEV_REDUCED_PHYS_BITS
```

Any pointers?

Thanks!

**Comment by purpleidea** [comment]
Seems to be from this commit: https://github.com/libvirt/libvirt-go/commit/1d1aa561925adf035ec3285dc6fb43c6894e2670

Which didn't even pass tests before it was merged :/
https://travis-ci.org/libvirt/libvirt-go/builds/393499516

Failed with the exact same errors...
https://travis-ci.org/libvirt/libvirt-go/jobs/393499541#L3566

**Comment by purpleidea** [comment]
Fix in: https://github.com/libvirt/libvirt-go/pull/37

**Comment by berrange** [comment]
The commit passed tests with current libvirt, only old libvirt was broken.

There are git tags for each release if you want to have a stable version to test against, as this is always liable to happen on git master.

**Comment by berrange** [comment]
Those are *post commit* tests. We don't require testing against every possible combination before committing - the post commit tests identify any mistakes and we'll fix them when they occurr, as we've done here.

**Comment by purpleidea** [comment]
@berrange I'm not entirely sure I understand what's going on. Is there some doc about this I can read? All I know is that I'm trying to use the _latest_ git master version of libvirt-go, and it recently broke (now it seems fixed right after).

**Comment by berrange** [comment]
There's no doc, but what i've mentioned above describes it.  We aim to keep master working correctly, but don't guarantee it, as we don't mandate exhaustive pre-commit testing. The majority of our automated testing happens post-commit, so there's inevitably risk that master will sometimes be broken when things get missed in code review.  So if you need a guaranteed working version for your own testing use a formal release tag instead of git master.

**Comment by purpleidea** [comment]
@berrange Why wouldn't it be better to test _before_ the mistake is made in git master??

**Comment by purpleidea** [comment]
> That optimizes for the case where developers screw up by delaying ability to commit stuff for everyone.

Yeah it delays everyone who depends on git master building, even other developers rebasing their patches :/

> proprietary tools like travis

It's not: all the code is here: https://github.com/travis-ci/
