### ISSUE TITLE
faced error: this function is not supported by the connection driver: virDomainGetHostname

### ISSUE THREAD

**Issue by sunkevin6** [libvirt/libvirt-go#39]
Hi 
I am trying to get VM hostname by dom.GetHostname(0) function.
But I faced the following error,
"MESSAGE":"Failed to invoke getHostname","error":"virError(Code=3, Domain=20, Message='this function is not supported by the connection driver: virDomainGetHostname')"

My code is running inside docker, and try to collect libvirt metrics of VMs on the node.

This is the node information,
[hv] root@pok1-qz1-sr1-rk026-s22:~# dpkg -l | grep libvirt
ii  libvirt-bin                                         4.1.0-2ibm3                                                  amd64        programs for the libvirt library
ii  libvirt-clients                                     4.1.0-2ibm3                                                  amd64        Programs for the libvirt library
ii  libvirt-daemon                                      4.1.0-2ibm3                                                  amd64        Virtualization daemon
ii  libvirt-daemon-system                               4.1.0-2ibm3                                                  amd64        Libvirt daemon configuration files
ii  libvirt0:amd64                                      4.1.0-2ibm3                                                  amd64        library for interfacing with different virtualization systems
[hv] root@pok1-qz1-sr1-rk026-s22:~# lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:    18.04
Codename:    bionic

and this is the docker image information
root@libvirtmetrics-9mpqv:/# dpkg -l | grep libvirt 
ii  libvirt-bin                          4.0.0-1ubuntu8.5                       amd64        programs for the libvirt library
ii  libvirt-clients                      4.0.0-1ubuntu8.5                       amd64        Programs for the libvirt library
ii  libvirt-daemon                       4.0.0-1ubuntu8.5                       amd64        Virtualization daemon
ii  libvirt-daemon-driver-storage-rbd    4.0.0-1ubuntu8.5                       amd64        Virtualization daemon RBD storage driver
ii  libvirt-daemon-system                4.0.0-1ubuntu8.5                       amd64        Libvirt daemon configuration files
ii  libvirt0:amd64                       4.0.0-1ubuntu8.5                       amd64        library for interfacing with different virtualization systems

I want to know which version of ubuntu and libvirt will support dom.GetHostname(0) function? 
thanks.

**Comment by berrange** [comment]
This simply indicates that the hypervisor you're using doesn't support the API and isn't a bug in the Go bindings. You can see support info in https://libvirt.org/hvsupport.html
