### ISSUE TITLE
Missing tag for v4.9.0 release

### ISSUE THREAD

**Issue by mrqwer88** [libvirt/libvirt-go#42]
Hello!

Looks like tag "v4.9.0" for libvirt  v4.9.0 (2018-11-04 https://libvirt.org/news.html ) is missed.
I cannot find it on https://libvirt.org/git/?p=libvirt-go.git;a=tags , and on this github and gitlab mirrors too.

**Comment by berrange** [comment]
There were no public API additions in v4.9.0, so there is nothing new that required tagging in Go bindings. The next tag will thus be v4.10.0
