### ISSUE TITLE
call func ConnectLibvirt error 

### ISSUE THREAD

**Issue by KevinDavidMitnick** [libvirt/libvirt-go#43]
Can not connect libvirt, err is: virError(Code=38, Domain=0, Message='Failed to make pipe: Too many open files')

**Comment by berrange** [comment]
That's pretty self-explanatory - your user account has opened too many file handles and hit the system ulimit for max files. There's nothing libvirt can do about this. You have to fix whatever is creating too many files, or raise the ulimit.
