### ISSUE TITLE
Disk Latency for Domain

### ISSUE THREAD

**Issue by datnt53** [libvirt/libvirt-go#47]
I'm testing latency disk of domain but `WrTotalTimes`, `RdTotalTimes`, `FlushTotalTimes` not return in `func (d *Domain) BlockStats(path string)`.

I don't know these variable match with what functions in `cStats`.
Please help me!!

Many thanks!

**Comment by clefchou** [comment]
I'm using libvirt-exporter to collect metrics from blocks. It seems that  WrTotalTimesSet, RdTotalTimesSet, and FlushTotalTimesSet is always read as false.

Please help

**Comment by datnt53** [comment]
You can use `blockStatsFlags` to get all metric related to Block Statistics.
This function will extract data by list `[metric1: value1, metric2: value2]`, you must exactly get metrics thay you need.
