### ISSUE TITLE
function not supported by the connection driver: virStreamSend

### ISSUE THREAD

**Issue by dsbrng25b** [libvirt/libvirt-go#48]
I try to to upload an image to libvirt (code: [main.txt](https://github.com/libvirt/libvirt-go/files/3311921/main.txt)). Currently I get the following error:
```
virError(Code=3, Domain=38, Message='this function is not supported by the connection driver: virStreamSend')
```
What is the problem here? How do one use the Upload function and the Stream struct correctly?

**Comment by berrange** [comment]
You've got the calls in the wrong order. You need to call the "Upload" function first. This connects the stream object to the storage volume object. You can then Send to the stream to upload data, and finally call Finish.

**Comment by dsbrng25b** [comment]
Thank you for your answer. Its working now.
As far as I understood from the README, the idea of libvirt-go is to stay in sync with the libvirt C API. Nevertheless, would it be possible to add Read, Write and Close methods to Stream as aliases to Send, Recv and Finish? This would be very piratical since a lot of APIs in go accept io.Reader, io.Writer etc.
