### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by OnitiFR** [libvirt/libvirt-go#49]
While updating my project, compilation failed with the following:
```
# github.com/libvirt/libvirt-go
go/src/github.com/libvirt/libvirt-go/network_port.go:126: not enough arguments to return
	have (Error)
	want (string, error)
```
A string is missing for the first arguement of the return:
```return makeNotImplementedError("virNetworkPortDelete")```

I'm a bit surprised to see this error that seems related to an 8 days old commit. Should I be scared? :)

Edit: I've just seen the Travis badge switching from "pass" to "failed", I'm a bit reassured ;)

**Comment by OnitiFR** [comment]
The makeNotImplementedError() parameter is not good either, seems copy/pasted from `func (n *NetworkPort) Delete(flags uint) error` a few lines above.

**Comment by berrange** [comment]
I mistakenly pushed the patch without committing unstaged changes. The fix will sync to github shortly.
