### ISSUE TITLE
Compilation error with latest release

### ISSUE THREAD

**Issue by OnitiFR** [libvirt/libvirt-go#50]
Hi,

I had compilation issues with `HEAD` a few weeks ago so I decided to use tagged release instead, thanks to `gopkg.in`. But I now have the same compilation issue with 5.6.0:
```
../../../gopkg.in/libvirt/libvirt-go.v5/domain.go:2071:13: could not determine kind of name for C.virDomainCheckpointPtr
../../../gopkg.in/libvirt/libvirt-go.v5/domain.go:2073:12: could not determine kind of name for C.virDomainListAllCheckpointsWrapper
cgo: 
gcc errors for preamble:
In file included from ../../../gopkg.in/libvirt/libvirt-go.v5/domain.go:32:
./domain_wrapper.h:995:8: error: unknown type name 'virDomainCheckpointPtr'; did you mean 'virDomainSnapshotPtr'?
  995 |        virDomainCheckpointPtr **cps,
      |        ^~~~~~~~~~~~~~~~~~~~~~
      |        virDomainSnapshotPtr
./domain_wrapper.h:999:1: error: unknown type name 'virDomainCheckpointPtr'; did you mean 'virDomainSnapshotPtr'?
  999 | virDomainCheckpointPtr
      | ^~~~~~~~~~~~~~~~~~~~~~
      | virDomainSnapshotPtr
./domain_wrapper.h:1005:1: error: unknown type name 'virDomainCheckpointPtr'; did you mean 'virDomainSnapshotPtr'?
 1005 | virDomainCheckpointPtr
      | ^~~~~~~~~~~~~~~~~~~~~~
      | virDomainSnapshotPtr
```
How can I fix this? What's the safest way to import this library?

**Comment by berrange** [comment]
This mistake was fixed after 5.6.0 was tagged in

commit 21453068bc721e28f1843c71b3514880c354d3f3
Author: Daniel P. Berrangé <berrange@redhat.com>
Date:   Tue Aug 6 15:17:54 2019 +0100

    Add missing include for compat def of virDomainCheckpointPtr
    
    Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>

**Comment by OnitiFR** [comment]
Thanks for your very quick answer. Can you push a new tag including this commit?
Also: can I trust any new release as "stable"? (and consider that the current issue is just a hiccup) or is there any other way to `import` libvirt-go in my code?

**Comment by berrange** [comment]
Normally the tagged releases are the best to use. This was just a rare screwup.

Assuming you don't actually need any of the new API bindings added in 5.6.0, then you can just pick the previous stable tag in stead v5.5.0

The next release 5.7.0 will be in 2 weeks time.

**Comment by OnitiFR** [comment]
I understand. It does not match my setup (can't use go modules because we use Go 1.10 on production servers and `gopkg.in` automatically use the latest v5 release so I can't pick a specific release) that's why a v5.6.1 would have been a great help ;)

I'll try to find another way, then.

**Comment by berrange** [comment]
Ah i see what its an issue. I'll add a v5.6.1 tag to solve this for you.

**Comment by OnitiFR** [comment]
Nice, it's very helpful! Thanks a lot.
