### ISSUE TITLE
when using qemu+ssh connect，can't close the connection

### ISSUE THREAD

**Issue by wucl202000** [libvirt/libvirt-go#51]
I use qemu+ssh to connect to remote hypervisor. like this：

`libvirt.NewConnect("qemu+ssh://root@x.x.x.x/system?socket=/var/run/libvirt/libvirt-sock")`

When I am done, I exec conn.Close(), and it return 1, err == nil. But actually, I found  ssh connection  still on my system. like this:

`ssh -l root--x.x.x.x  sh-c 'if 'nc' -q 2>&1 | grep "requires an argument" >/dev/null 2>&1; then ARG=-q0;else ARG=;fi;'nc' $ARG -U /var/run/libvirt/libvirt-sock'`

How can I close these connection?

**Comment by berrange** [comment]
Presumably you have used one or more `libvirt.Domain` objects ? Each domain (and other libvirt object) will hold a reference on the `libvirt.Connect` object, so it won't actually be closed until you release all those.

**Comment by wucl202000** [comment]
> Presumably you have used one or more `libvirt.Domain` objects ? Each domain (and other libvirt object) will hold a reference on the `libvirt.Connect` object, so it won't actually be closed until you release all those.

You are right. Thanks a lot.
Actually, I used defer to free the domain object in a loop, it didn't correctly Free the domain object. So when I called libvirt.Connect.Close(), it didn't close the connection correctly.
I checked and correct it.
It works as I wish now.
