### ISSUE TITLE
static compilation

### ISSUE THREAD

**Issue by treywelsh** [libvirt/libvirt-go#52]
Hi,

Building a binary using libvirt-go adds a bunch of dependencies to shared objects.
Is it possible to build statically to remove all these dependencies ?

Just to be clear I first installed libvirt-devel package.

So, when I build my project without using libvirt-go:
```
go build -v -ldflags '-s -w -extldflags "-static"' ./cmd/project/main.go
ldd main
	linux-vdso.so.1 =>  (0x00007ffc6af7f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa091f86000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa091bb8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa0921a2000)
```

using libvirt-go:
```
go build -v -ldflags '-s -w' ./cmd/project/main.go 
ldd main
	linux-vdso.so.1 =>  (0x00007ffd109ba000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f306fa18000)
	libvirt-lxc.so.0 => /lib64/libvirt-lxc.so.0 (0x00007f306f814000)
	libvirt-qemu.so.0 => /lib64/libvirt-qemu.so.0 (0x00007f306f610000)
	libvirt.so.0 => /lib64/libvirt.so.0 (0x00007f306f031000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f306ec63000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f306fc34000)
	libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007f306ea5d000)
	libyajl.so.2 => /lib64/libyajl.so.2 (0x00007f306e853000)
...
	libffi.so.6 => /lib64/libffi.so.6 (0x00007f30666f8000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f3066486000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f3066023000)
	libelf.so.1 => /lib64/libelf.so.1 (0x00007f3065e0b000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f3065bfb000)
```
(around 70 lines, but I shortened the content)

When I try to compile statically, I get:
```
go build -v -ldflags '-s -w -extldflags "-static"' ./cmd/project/main.go 
# command-line-arguments
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lvirt-lxc
/usr/bin/ld: cannot find -lvirt-lxc
/usr/bin/ld: cannot find -lvirt-qemu
/usr/bin/ld: cannot find -lvirt-qemu
/usr/bin/ld: cannot find -lvirt
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
```

I'm stuck here, I can't find any static version of libvirt ?
I currently work with a CentOS Linux release 7.7.1908 (Core)

Thank you and have a good day :)

**Comment by berrange** [comment]
Libvirt does not support being built as a static library I'm afraid.

**Comment by treywelsh** [comment]
Ok, now it's clear :)

thank you for your fast response, I close the ticket as it's not possible as is

**Comment by purpleidea** [comment]
@berrange 

> Libvirt does not support being built as a static library I'm afraid.

What would it take to make this possible? It's a pain point for https://github.com/purpleidea/mgmt/ because we need to build a different golang binary for each distro because of this, since they all have a different version of libvirt libraries that's packaged there.
