### ISSUE TITLE
How to attach device persistently

### ISSUE THREAD

**Issue by YoungjuWang** [libvirt/libvirt-go#68]
Hello,

I used " func (*Domain) AttachDeviceFlags " function to attach device to VM.
I want to use it like 'virsh attach-device --config' option.

I tried to use "DOMAIN_DEVICE_MODIFY_LIVE" and "DOMAIN_DEVICE_MODIFY_CONFIG" like below, but It doesn't work. attached interface in VM has different MAC address with in domain xml file

```
		err := dom.AttachDeviceFlags(x, libvirt.DOMAIN_DEVICE_MODIFY_LIVE)
		if err != nil {
			log.Fatal(err)
		}

		err = dom.AttachDeviceFlags(x, libvirt.DOMAIN_DEVICE_MODIFY_CONFIG)
		if err != nil {
			log.Fatal(err)
		}
```

How can I use flag for persistent attachment?

**Comment by YoungjuWang** [comment]
I did it.

```
		err := dom.AttachDeviceFlags(x, libvirt.DOMAIN_DEVICE_MODIFY_CONFIG^libvirt.DOMAIN_DEVICE_MODIFY_LIVE)
		if err != nil {
			log.Fatal(err)
		}
```

But I can understand How it works. Can someone explain for me?

**Comment by berrange** [comment]
I'm assuming that the xml document you are providing does not contain any MAC address. Thus libvirt generates a random one when it parses the XML. In the first example you're using 2 API calls, so 2 different random MAC addrs will be generated. In the second example you only have 1 API calls, so only 1 random MAC addr is used for both operations

**Comment by YoungjuWang** [comment]
@berrange 
Thank you for your answer. But I tired & but it doesn't work only ^ works.

How can i understand it? Can you help me?


```
# It doesn't work
		err := dom.AttachDeviceFlags(x, libvirt.DOMAIN_DEVICE_MODIFY_CONFIG&libvirt.DOMAIN_DEVICE_MODIFY_LIVE)

# It works
		err := dom.AttachDeviceFlags(x, libvirt.DOMAIN_DEVICE_MODIFY_CONFIG^libvirt.DOMAIN_DEVICE_MODIFY_LIVE)

```

**Comment by berrange** [comment]
The first is a bitwise AND operation, the second is a bitwise OR operation.  To set both flags you need OR, hence the second works.

**Comment by YoungjuWang** [comment]
Thank you for your comment. I hope you have a good day
